spring:
  datasource:
    url: jdbc:h2:file:~/h2/test_db;
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2-console